const pool = require('./db');
const bcrypt = require('bcryptjs');
const crypto = require('crypto');

async function seed() {
  const client = await pool.connect();
  try {
    await client.query(`
      CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        email VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        name VARCHAR(255) NOT NULL,
        role VARCHAR(50) DEFAULT 'admin',
        created_at TIMESTAMP DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS services (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        slug VARCHAR(255) UNIQUE NOT NULL,
        tagline VARCHAR(500),
        description TEXT,
        icon VARCHAR(50),
        features JSONB DEFAULT '[]',
        sort_order INT DEFAULT 0,
        published BOOLEAN DEFAULT true,
        created_at TIMESTAMP DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS industries (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        slug VARCHAR(255) UNIQUE NOT NULL,
        description TEXT,
        challenges TEXT,
        approach TEXT,
        related_services JSONB DEFAULT '[]',
        published BOOLEAN DEFAULT true,
        created_at TIMESTAMP DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS insights (
        id SERIAL PRIMARY KEY,
        title VARCHAR(500) NOT NULL,
        slug VARCHAR(500) UNIQUE NOT NULL,
        summary TEXT,
        content TEXT,
        category VARCHAR(100),
        domain VARCHAR(100),
        author VARCHAR(255) DEFAULT 'Akarsu Advisory',
        published BOOLEAN DEFAULT false,
        featured BOOLEAN DEFAULT false,
        created_at TIMESTAMP DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS case_studies (
        id SERIAL PRIMARY KEY,
        title VARCHAR(500) NOT NULL,
        slug VARCHAR(500) UNIQUE NOT NULL,
        industry VARCHAR(255),
        challenge TEXT,
        approach TEXT,
        result TEXT,
        metrics JSONB DEFAULT '{}',
        published BOOLEAN DEFAULT true,
        created_at TIMESTAMP DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS testimonials (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        title VARCHAR(255),
        company VARCHAR(255),
        quote TEXT NOT NULL,
        rating INT DEFAULT 5,
        published BOOLEAN DEFAULT true,
        created_at TIMESTAMP DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS consultations (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL,
        company VARCHAR(255),
        phone VARCHAR(50),
        service_interest VARCHAR(255),
        message TEXT,
        preferred_date DATE,
        preferred_time VARCHAR(50),
        status VARCHAR(50) DEFAULT 'pending',
        notes TEXT,
        created_at TIMESTAMP DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS contacts (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL,
        company VARCHAR(255),
        phone VARCHAR(50),
        subject VARCHAR(500),
        message TEXT,
        status VARCHAR(50) DEFAULT 'new',
        created_at TIMESTAMP DEFAULT NOW()
      );
    `);

    // Create or reset admin user
    const randomPassword = crypto.randomBytes(12).toString('base64url').slice(0, 16);
    const hash = await bcrypt.hash(randomPassword, 10);
    const exists = await client.query("SELECT id FROM users WHERE email = 'admin@akarsuadvisory.com'");
    if (exists.rows.length === 0) {
      await client.query(
        "INSERT INTO users (email, password, name, role) VALUES ($1, $2, $3, $4)",
        ['admin@akarsuadvisory.com', hash, 'Admin', 'admin']
      );
    } else {
      await client.query(
        "UPDATE users SET password = $1 WHERE email = 'admin@akarsuadvisory.com'",
        [hash]
      );
    }
    console.log(`Admin password: ${randomPassword}`);

    // Seed services (clear and reseed)
    await client.query("DELETE FROM services");
    {
      const services = [
        { name: 'Financial Statement Review & Analysis', slug: 'financial-statement-review', tagline: 'We break down the numbers so you can make informed decisions.', description: 'Profit & Loss, Balance Sheet, Cash Flow Statement, metrics/KPIs, working capital — we break down the numbers so you can make informed decisions.', features: JSON.stringify(['Profit & Loss Analysis', 'Balance Sheet Review', 'Cash Flow Statement', 'Key Metrics & KPIs', 'Working Capital Analysis', 'Financial Health Assessment']), sort_order: 1 },
        { name: 'Annual Budget Planning', slug: 'annual-budget-planning', tagline: 'A clear financial roadmap for the year ahead.', description: 'Structured annual budgets aligned with your business goals, giving you a clear financial roadmap for the year ahead.', features: JSON.stringify(['Goal-Aligned Budgeting', 'Revenue Projections', 'Expense Planning', 'Capital Allocation', 'Department Budgets', 'Variance Analysis Framework']), sort_order: 2 },
        { name: 'Monthly P&L Forecasting', slug: 'monthly-pl-forecasting', tagline: 'Anticipate revenue trends and manage expenses proactively.', description: 'Stay ahead with monthly profit and loss projections that help you anticipate revenue trends and manage expenses proactively.', features: JSON.stringify(['Revenue Trend Analysis', 'Expense Tracking', 'Margin Forecasting', 'Variance Reporting', 'Rolling Forecasts', 'Performance Benchmarking']), sort_order: 3 },
        { name: 'Weekly Cash Flow Forecasting', slug: 'weekly-cash-flow-forecasting', tagline: 'Real-time visibility into your cash position.', description: 'Real-time visibility into your cash position with weekly forecasts so you never get caught off guard.', features: JSON.stringify(['Weekly Cash Projections', 'Receivables Tracking', 'Payables Management', 'Cash Buffer Planning', 'Liquidity Analysis', 'Alert Triggers']), sort_order: 4 },
        { name: 'Scenario Modeling', slug: 'scenario-modeling', tagline: 'Data-driven modeling for key business decisions.', description: 'Data-driven modeling for key decisions — capital expenditures, operating expense adjustments, and more.', features: JSON.stringify(['Capital Expenditure Analysis', 'Operating Expense Modeling', 'Growth Scenario Planning', 'Risk Assessment', 'What-If Analysis', 'Decision Support']), sort_order: 5 },
        { name: 'Accounts Receivable Management', slug: 'accounts-receivable-management', tagline: 'Get paid faster and improve your cash cycle.', description: 'We analyze your receivables aging, identify collection bottlenecks, and implement processes to shorten your cash conversion cycle.', features: JSON.stringify(['AR Aging Analysis', 'Collection Process Design', 'Payment Terms Optimization', 'Customer Credit Assessment', 'Automated Reminders Setup', 'Bad Debt Reduction']), sort_order: 6 },
        { name: 'Accounts Payable Optimization', slug: 'accounts-payable-optimization', tagline: 'Manage outflows strategically to preserve cash.', description: 'We help you optimize payment timing, negotiate better vendor terms, and build a payables strategy that supports your cash flow.', features: JSON.stringify(['AP Aging Analysis', 'Vendor Term Negotiation', 'Payment Scheduling', 'Early Payment Discount Analysis', 'Expense Categorization', 'Cash Preservation Strategy']), sort_order: 7 },
        { name: 'KPI Dashboard & Reporting', slug: 'kpi-dashboard-reporting', tagline: 'Track the metrics that actually drive your business.', description: 'We build custom KPI dashboards so you can monitor your financial health at a glance and make data-driven decisions every week.', features: JSON.stringify(['Custom KPI Selection', 'Weekly Dashboard Reports', 'Trend Analysis', 'Benchmark Comparisons', 'Visual Financial Summaries', 'Automated Reporting']), sort_order: 8 },
        { name: 'Break-Even Analysis', slug: 'break-even-analysis', tagline: 'Know exactly when your investment pays off.', description: 'We calculate your break-even point for new products, locations, hires, or investments so you can plan with confidence.', features: JSON.stringify(['Fixed vs Variable Cost Analysis', 'Revenue Threshold Modeling', 'Product-Level Break-Even', 'Location Expansion Analysis', 'Hire ROI Calculation', 'Timeline Projections']), sort_order: 9 },
        { name: 'Pricing Strategy & Analysis', slug: 'pricing-strategy', tagline: 'Price with data, not guesswork.', description: 'We analyze your true costs, margins, and market position to help you set prices that maximize profitability without losing customers.', features: JSON.stringify(['Cost-Plus Analysis', 'Margin by Product/Service', 'Competitive Pricing Review', 'Volume Discount Modeling', 'Price Sensitivity Testing', 'Profitability Optimization']), sort_order: 10 },
        { name: 'Debt & Financing Advisory', slug: 'debt-financing-advisory', tagline: 'Make smart borrowing decisions backed by data.', description: 'We help you evaluate loan options, model debt service capacity, and determine the right financing structure for your growth plans.', features: JSON.stringify(['Loan Comparison Analysis', 'Debt Service Coverage Ratio', 'Refinancing Evaluation', 'SBA Loan Guidance', 'Line of Credit Strategy', 'Debt Payoff Modeling']), sort_order: 11 },
        { name: 'Inventory & COGS Analysis', slug: 'inventory-cogs-analysis', tagline: 'Understand your true cost of goods sold.', description: 'We analyze your inventory costs, turnover rates, and COGS to help you improve margins and reduce waste.', features: JSON.stringify(['COGS Breakdown', 'Inventory Turnover Analysis', 'Shrinkage & Waste Tracking', 'Reorder Point Optimization', 'Supplier Cost Comparison', 'Margin Improvement Plan']), sort_order: 12 },
        { name: 'Fractional CFO Services', slug: 'fractional-cfo', tagline: 'Executive financial leadership without the full-time cost.', description: 'Get a dedicated financial partner who attends your meetings, advises on strategy, and keeps your finances on track — on a part-time basis.', features: JSON.stringify(['Weekly Financial Reviews', 'Strategic Planning Sessions', 'Board & Investor Reporting', 'Team Financial Training', 'Vendor & Bank Negotiations', 'Growth Strategy Support']), sort_order: 13 },
        { name: 'Financial Process & Systems Setup', slug: 'financial-systems-setup', tagline: 'Build the financial infrastructure your business needs.', description: 'We help you select and set up the right accounting software, reporting tools, and financial processes so your numbers are always accurate and accessible.', features: JSON.stringify(['Accounting Software Selection', 'Chart of Accounts Setup', 'Reporting Template Design', 'Process Documentation', 'Team Training', 'Monthly Close Process']), sort_order: 14 },
      ];

      for (const s of services) {
        await client.query(
          "INSERT INTO services (name, slug, tagline, description, features, sort_order) VALUES ($1,$2,$3,$4,$5,$6)",
          [s.name, s.slug, s.tagline, s.description, s.features, s.sort_order]
        );
      }
    }

    // Seed industries (clear and reseed)
    await client.query("DELETE FROM industries");
    {
      const industries = [
        { name: 'Tax Planning & Strategy', slug: 'tax-planning', description: 'Proactive tax planning and strategy for small businesses to minimize tax liability, maximize deductions, and ensure compliance year-round.', challenges: 'Many small business owners only think about taxes at filing time, missing quarterly planning opportunities, overpaying due to poor entity structure, and failing to capture all eligible deductions and credits.', approach: 'We provide year-round tax planning — quarterly estimates, entity structure reviews, deduction optimization, and year-end strategies. We coordinate with your CPA to ensure every dollar is working for you.' },
        { name: 'Bookkeeping & Accounting', slug: 'bookkeeping-accounting', description: 'Accurate, timely bookkeeping and accounting services that give you clean books, reliable financial statements, and confidence in your numbers.', challenges: 'Messy books, uncategorized transactions, late reconciliations, unreliable financial statements, and lack of visibility into true business performance. Many owners cannot trust their own numbers.', approach: 'We clean up your books, set up proper chart of accounts, implement monthly close processes, and deliver financial statements you can actually rely on for decision-making.' },
        { name: 'Cash Flow Management', slug: 'cash-flow-management', description: 'Expert cash flow forecasting and management to ensure your business always has the liquidity to operate, grow, and weather unexpected challenges.', challenges: 'Running out of cash despite being profitable on paper, inability to predict cash shortfalls, timing gaps between receivables and payables, and lack of a cash buffer for emergencies.', approach: 'We build 13-week rolling cash flow forecasts, identify timing gaps, optimize payment cycles, and create cash reserve strategies so you never get caught off guard.' },
        { name: 'Financial Reporting & Compliance', slug: 'financial-reporting', description: 'Professional financial reporting, regulatory compliance, and management reporting that meets the needs of stakeholders, lenders, and regulators.', challenges: 'Inconsistent reporting formats, inability to produce reports on demand, non-compliance with GAAP or regulatory requirements, and lack of meaningful management reports for decision-making.', approach: 'We design custom reporting packages — monthly management reports, board-ready presentations, lender-compliant financials, and automated dashboards that give you real-time visibility.' },
        { name: 'Budgeting & Forecasting', slug: 'budgeting-forecasting', description: 'Data-driven budgeting and financial forecasting that gives your business a clear roadmap and the ability to plan for multiple scenarios.', challenges: 'No formal budget, unrealistic projections, inability to track variance, no rolling forecasts, and making major spending decisions without financial models to support them.', approach: 'We build annual budgets, monthly rolling forecasts, and scenario models. We track actuals vs. budget every month so you can course-correct before small variances become big problems.' },
        { name: 'Accounts Receivable & Collections', slug: 'accounts-receivable', description: 'Optimize your receivables process to get paid faster, reduce bad debt, and improve your cash conversion cycle.', challenges: 'Slow-paying customers, high days sales outstanding (DSO), no systematic follow-up process, bad debt write-offs, and cash tied up in unpaid invoices for 60-90+ days.', approach: 'We analyze your AR aging, redesign your invoicing and collections process, implement early payment incentives, and build automated follow-up systems to shorten your cash cycle.' },
        { name: 'Accounts Payable & Vendor Management', slug: 'accounts-payable', description: 'Strategic accounts payable management to optimize payment timing, negotiate better vendor terms, and preserve cash without damaging relationships.', challenges: 'Paying vendors too early and hurting cash flow, missing early payment discounts, poor vendor term negotiations, duplicate payments, and no strategic approach to outgoing cash.', approach: 'We optimize your payment calendar, negotiate extended terms with key vendors, identify early payment discount opportunities, and build an AP strategy that preserves cash while maintaining strong vendor relationships.' },
        { name: 'Payroll & Compensation Planning', slug: 'payroll-compensation', description: 'Payroll optimization and compensation planning that balances employee satisfaction with business profitability and tax efficiency.', challenges: 'Labor costs consuming too much revenue, inefficient payroll structures, no benchmark data for compensation, tax-inefficient owner compensation, and difficulty modeling the true cost of new hires.', approach: 'We analyze your payroll as a percentage of revenue, benchmark compensation against market rates, optimize owner compensation for tax efficiency, and model the full cost of hiring decisions before you commit.' },
        { name: 'Cost Accounting & COGS Analysis', slug: 'cost-accounting', description: 'Detailed cost accounting and COGS analysis to understand your true unit costs, product margins, and opportunities to improve profitability.', challenges: 'Not knowing true cost per product or service, inaccurate COGS calculations, hidden costs buried in overhead, shrinkage and waste going untracked, and pricing based on guesswork rather than data.', approach: 'We break down your costs at the product and service level, allocate overhead accurately, track waste and shrinkage, and build cost models that let you price with confidence and protect margins.' },
        { name: 'Audit Preparation & Support', slug: 'audit-preparation', description: 'Comprehensive audit preparation services to ensure your books, documentation, and financial records are ready for external audits or reviews.', challenges: 'Disorganized records, missing documentation, unreconciled accounts, fear of audit findings, and last-minute scrambling that disrupts normal business operations during audit season.', approach: 'We prepare your books months in advance — reconcile all accounts, organize supporting documentation, resolve discrepancies, and serve as your liaison during the audit process so you can focus on running your business.' },
        { name: 'Financial Systems & Technology', slug: 'financial-systems', description: 'Selection, implementation, and optimization of accounting software, financial tools, and reporting systems for modern small businesses.', challenges: 'Using the wrong accounting software, manual spreadsheet processes, disconnected financial systems, no automated reporting, and spending hours on tasks that should take minutes.', approach: 'We evaluate your current tech stack, recommend the right tools (QuickBooks, Xero, FreshBooks, etc.), handle migration and setup, build automated reporting, and train your team to use everything effectively.' },
        { name: 'Treasury & Working Capital', slug: 'treasury-working-capital', description: 'Working capital optimization and treasury management to ensure your business has the liquidity to operate efficiently and seize growth opportunities.', challenges: 'Cash trapped in receivables and inventory, negative working capital cycles, no cash reserve strategy, inefficient banking relationships, and inability to fund growth from operations.', approach: 'We optimize your working capital cycle — speeding up collections, managing payables strategically, right-sizing inventory, and building treasury management practices that maximize the value of every dollar.' },
        { name: 'Business Valuation & Exit Planning', slug: 'business-valuation', description: 'Business valuation services and exit planning for owners who want to understand what their business is worth and how to maximize its value.', challenges: 'No idea what the business is actually worth, no exit strategy, value concentrated in the owner, financial records that would not survive buyer due diligence, and leaving money on the table at sale.', approach: 'We provide formal business valuations using multiple methodologies, identify value drivers and detractors, build multi-year plans to increase enterprise value, and prepare your financials for buyer due diligence.' },
        { name: 'Risk Management & Internal Controls', slug: 'risk-management', description: 'Financial risk assessment and internal control design to protect your business from fraud, errors, and financial mismanagement.', challenges: 'No segregation of duties, lack of approval workflows, exposure to employee fraud, no financial policies or procedures, and inability to detect errors or irregularities until it is too late.', approach: 'We assess your financial risk profile, design internal controls appropriate for your size, implement approval workflows, create financial policies and procedures, and set up monitoring systems to catch issues early.' },
        { name: 'Mergers & Acquisitions Advisory', slug: 'mergers-acquisitions', description: 'Financial due diligence, deal structuring, and integration planning for small business acquisitions, mergers, and partnerships.', challenges: 'Overpaying for acquisitions due to poor financial analysis, missing hidden liabilities in due diligence, structuring deals tax-inefficiently, and failing to plan for post-merger financial integration.', approach: 'We perform thorough financial due diligence, build deal models with multiple scenarios, identify hidden risks and liabilities, structure transactions for tax efficiency, and create integration plans that capture synergies quickly.' },
      ];

      for (const ind of industries) {
        await client.query(
          "INSERT INTO industries (name, slug, description, challenges, approach) VALUES ($1,$2,$3,$4,$5)",
          [ind.name, ind.slug, ind.description, ind.challenges, ind.approach]
        );
      }
    }

    // Seed case studies (clear and reseed)
    await client.query("DELETE FROM case_studies");
    {
      const caseStudies = [
        { title: 'Tax Strategy Saved Retailer $85K in First Year', slug: 'tax-strategy-retailer', industry: 'Tax Planning & Strategy', challenge: 'A multi-location retail business was overpaying taxes by $85K annually due to incorrect entity structure, missed deductions, and no quarterly tax planning.', approach: 'We restructured the business as an S-Corp, implemented quarterly tax planning sessions, identified $45K in missed deductions, and coordinated with their CPA on year-end strategies.', result: 'Reduced annual tax liability by $85K in the first year. Owner now pays quarterly estimates accurately and has a year-round tax strategy instead of a once-a-year scramble.', metrics: JSON.stringify({ tax_savings: '$85K/year', deductions_found: '$45K missed', structure: 'S-Corp conversion', planning: 'Quarterly reviews' }) },
        { title: 'Bookkeeping Cleanup Reveals Hidden Profitability', slug: 'bookkeeping-cleanup', industry: 'Bookkeeping & Accounting', challenge: 'A growing services company had 18 months of unreconciled books, miscategorized transactions, and financial statements that nobody trusted. The owner was making decisions blind.', approach: 'We performed a full bookkeeping cleanup — reconciled 18 months of bank and credit card statements, recategorized 2,400+ transactions, and rebuilt the chart of accounts from scratch.', result: 'Clean books revealed the business was 22% more profitable than the owner thought. Monthly close process now takes 3 days instead of never getting done. Lender approved a $250K line of credit based on accurate financials.', metrics: JSON.stringify({ months_reconciled: '18 months', transactions_fixed: '2,400+', profitability_discovered: '+22%', credit_approved: '$250K LOC' }) },
        { title: '13-Week Cash Flow Forecast Prevents Business Closure', slug: 'cash-flow-forecast-saves', industry: 'Cash Flow Management', challenge: 'A construction company doing $4M in revenue was 3 weeks away from missing payroll. Despite strong revenue, long payment cycles and front-loaded costs created a critical cash gap.', approach: 'We built a 13-week rolling cash flow forecast, identified $180K in receivables past 60 days, renegotiated payment terms with 3 key vendors, and established a $100K line of credit as a safety net.', result: 'Collected $120K in overdue receivables within 30 days. Never missed payroll. The owner now has weekly cash visibility and maintains a 6-week cash buffer at all times.', metrics: JSON.stringify({ receivables_collected: '$120K in 30 days', payroll_missed: 'Zero', cash_buffer: '6-week minimum', forecast: 'Weekly 13-week rolling' }) },
        { title: 'Custom Financial Reporting for Board-Ready Startup', slug: 'financial-reporting-startup', industry: 'Financial Reporting & Compliance', challenge: 'A venture-backed startup needed GAAP-compliant financials and investor-ready reporting but was producing inconsistent spreadsheets that eroded board confidence.', approach: 'We designed a complete reporting package — GAAP-compliant P&L, balance sheet, cash flow statement, KPI dashboard, and a monthly board deck with narrative analysis and burn rate projections.', result: 'Board meetings went from contentious to productive. Investors praised the financial transparency. The startup successfully raised a $2M Series A with financials that survived rigorous due diligence.', metrics: JSON.stringify({ funding_raised: '$2M Series A', compliance: 'GAAP-compliant', board_confidence: 'Fully restored', reporting: 'Monthly automated' }) },
        { title: 'Budget vs. Actual Tracking Transforms Restaurant Group', slug: 'budget-tracking-restaurant', industry: 'Budgeting & Forecasting', challenge: 'A 5-location restaurant group had never had a formal budget. Spending decisions were made ad hoc, resulting in $200K in unnecessary costs and no ability to plan for seasonal dips.', approach: 'We built location-level annual budgets, implemented monthly budget-vs-actual reviews, created rolling 12-month forecasts, and modeled 3 scenarios for a planned 6th location.', result: 'Cut $200K in unnecessary spending in year one. Monthly variance reviews caught a $15K vendor overcharge within 30 days. The 6th location opened on budget and hit breakeven on schedule.', metrics: JSON.stringify({ cost_reduction: '$200K', vendor_overcharge: '$15K caught', locations: '6th opened on budget', forecasting: '12-month rolling' }) },
        { title: 'AR Optimization Frees $340K in Trapped Cash', slug: 'ar-optimization', industry: 'Accounts Receivable & Collections', challenge: 'A professional services firm had $340K in outstanding receivables, with average DSO of 72 days. Two clients owed $95K past 90 days and the firm was borrowing to make payroll.', approach: 'We redesigned the invoicing process (invoice at delivery, not month-end), implemented automated payment reminders, introduced 2/10 net 30 terms, and created a weekly AR aging review ritual.', result: 'Reduced DSO from 72 to 34 days. Collected $280K of the outstanding $340K within 60 days. Eliminated the need for payroll borrowing. Early payment discount adoption reached 40% of clients.', metrics: JSON.stringify({ dso_reduction: '72 → 34 days', collected: '$280K in 60 days', borrowing: 'Eliminated', early_pay_adoption: '40%' }) },
        { title: 'AP Strategy Preserves $90K in Annual Cash Flow', slug: 'ap-strategy', industry: 'Accounts Payable & Vendor Management', challenge: 'A manufacturing company was paying all vendors on receipt, burning through cash unnecessarily. No vendor terms had been negotiated and the business was missing early payment discounts on the few vendors that offered them.', approach: 'We audited all vendor relationships, negotiated net-45 terms with 8 major suppliers, identified $12K/year in available early payment discounts, and built a strategic payment calendar aligned with cash inflows.', result: 'Freed up $90K in annual cash flow by extending payment timing. Captured $12K in early payment discounts on select vendors. Zero vendor relationship damage — all renegotiations were positive.', metrics: JSON.stringify({ cash_freed: '$90K annually', discounts_captured: '$12K/year', vendor_terms: 'Net-45 with 8 suppliers', relationships: 'All maintained' }) },
        { title: 'Payroll Restructure Saves Owner $48K in Taxes', slug: 'payroll-restructure', industry: 'Payroll & Compensation Planning', challenge: 'A business owner paying herself entirely via W-2 wages was overpaying self-employment and payroll taxes by $48K annually. Compensation structure had never been reviewed for tax efficiency.', approach: 'We analyzed the optimal salary-vs-distribution split for her S-Corp, benchmarked reasonable compensation, modeled the tax impact of different structures, and coordinated with her CPA for implementation.', result: 'Restructured compensation to save $48K in annual payroll taxes while remaining fully IRS-compliant. Also identified that 2 contractor positions should be W-2 employees, avoiding potential misclassification penalties.', metrics: JSON.stringify({ tax_savings: '$48K/year', structure: 'Salary + distributions', compliance: 'IRS-compliant', risk_avoided: 'Misclassification penalties' }) },
        { title: 'COGS Analysis Restores Margins from 12% to 28%', slug: 'cogs-analysis-margins', industry: 'Cost Accounting & COGS Analysis', challenge: 'A food manufacturing company saw gross margins shrink from 28% to 12% over 2 years. The owner assumed ingredient costs were the problem but had no product-level cost data to confirm.', approach: 'We built product-level COGS models for all 24 SKUs, tracked labor allocation per production run, identified $140K in annual waste and shrinkage, and benchmarked costs against industry standards.', result: 'Discovered 8 SKUs were being sold below true cost. Eliminated $140K in waste. Repriced the product line and discontinued 3 money-losing SKUs. Margins restored to 28% within 6 months.', metrics: JSON.stringify({ waste_eliminated: '$140K', unprofitable_skus: '8 repriced, 3 cut', margin_restoration: '12% → 28%', timeline: '6 months' }) },
        { title: 'Audit-Ready Books in 90 Days for Nonprofit', slug: 'audit-ready-nonprofit', industry: 'Audit Preparation & Support', challenge: 'A nonprofit with $3M in grant funding received notice of an upcoming audit but had 2 years of unreconciled accounts, missing documentation, and no restricted fund tracking.', approach: 'We deployed a 90-day audit readiness sprint — reconciled 24 months of accounts, rebuilt restricted vs. unrestricted fund tracking, organized all grant documentation, and prepared detailed audit workpapers.', result: 'Passed the audit with zero material findings. The auditor specifically praised the quality of documentation. The nonprofit secured an additional $500K grant based on the clean audit report.', metrics: JSON.stringify({ audit_result: 'Zero findings', timeline: '90-day sprint', grant_secured: '$500K new grant', months_reconciled: '24 months' }) },
        { title: 'QuickBooks Migration Saves 20 Hours Per Month', slug: 'quickbooks-migration', industry: 'Financial Systems & Technology', challenge: 'A growing company with 3 locations was still using spreadsheets for accounting. Monthly close took 2 weeks, reports were unreliable, and the owner spent 20+ hours monthly on manual data entry.', approach: 'We selected and implemented QuickBooks Online with multi-location tracking, migrated 3 years of historical data, set up automated bank feeds and recurring transactions, built custom reports, and trained the team.', result: 'Monthly close reduced from 2 weeks to 2 days. Owner reclaimed 20+ hours per month. Real-time dashboards replaced manual spreadsheets. All 3 locations now have consolidated and location-level reporting.', metrics: JSON.stringify({ time_saved: '20+ hours/month', close_time: '2 weeks → 2 days', locations: '3 consolidated', automation: 'Bank feeds + recurring' }) },
        { title: 'Working Capital Optimization Funds Growth Without Debt', slug: 'working-capital-optimization', industry: 'Treasury & Working Capital', challenge: 'A distribution company needed $300K to fund expansion but did not want to take on debt. Cash was trapped in slow-moving inventory and extended receivables with no systematic management.', approach: 'We analyzed the full working capital cycle, reduced inventory levels by identifying $180K in slow-moving stock, accelerated collections from 55 to 30 days DSO, and optimized payables timing.', result: 'Freed up $320K in working capital — more than enough to fund the expansion without a single dollar of debt. Working capital cycle improved from 68 days to 31 days.', metrics: JSON.stringify({ capital_freed: '$320K', inventory_reduced: '$180K', dso_improvement: '55 → 30 days', debt_taken: '$0' }) },
        { title: 'Business Valuation Increases Sale Price by $1.2M', slug: 'valuation-sale-price', industry: 'Business Valuation & Exit Planning', challenge: 'A business owner planning to sell in 2 years had no idea what the business was worth. A broker estimated $2M but the owner felt it should be higher — but had no data to support it.', approach: 'We performed a formal valuation using DCF, comparable transactions, and asset-based methods. Identified 5 value-destroying issues and built a 24-month value maximization plan targeting each one.', result: 'Initial valuation: $2.1M. After 24 months of executing the value plan — cleaned up books, diversified revenue, reduced owner dependency — the business sold for $3.3M. A $1.2M increase.', metrics: JSON.stringify({ initial_value: '$2.1M', sale_price: '$3.3M', value_increase: '$1.2M', timeline: '24 months' }) },
        { title: 'Internal Controls Prevent $75K Employee Fraud', slug: 'internal-controls-fraud', industry: 'Risk Management & Internal Controls', challenge: 'A retail business discovered a $75K embezzlement by a trusted bookkeeper who had been writing checks to a personal account for 3 years. There were zero financial controls in place.', approach: 'We designed a complete internal control framework — segregation of duties, dual-signature requirements, monthly bank reconciliation by an independent party, expense approval workflows, and surprise audits.', result: 'Implemented controls that would have caught the fraud within 30 days. Recovered $45K of the $75K through insurance and legal action. No financial irregularities detected in the 2 years since implementation.', metrics: JSON.stringify({ fraud_prevented: 'Ongoing', recovery: '$45K of $75K', detection_time: '30 days max', irregularities_since: 'Zero' }) },
        { title: 'Due Diligence Saves Buyer $400K on Acquisition', slug: 'due-diligence-acquisition', industry: 'Mergers & Acquisitions Advisory', challenge: 'A business owner was acquiring a competitor for $1.8M based on seller-provided financials. The deal looked good on paper but the buyer wanted independent financial verification before committing.', approach: 'We performed comprehensive financial due diligence — normalized earnings, analyzed customer concentration risk, identified $400K in undisclosed liabilities, and modeled post-acquisition cash flows under 3 scenarios.', result: 'Discovered $400K in hidden liabilities (deferred maintenance, pending lawsuit, understated payables). Renegotiated the deal from $1.8M to $1.3M. Post-acquisition integration went smoothly with no financial surprises.', metrics: JSON.stringify({ liabilities_found: '$400K hidden', deal_repriced: '$1.8M → $1.3M', savings: '$500K total', surprises: 'Zero post-close' }) },
      ];

      for (const cs of caseStudies) {
        await client.query(
          "INSERT INTO case_studies (title, slug, industry, challenge, approach, result, metrics) VALUES ($1,$2,$3,$4,$5,$6,$7)",
          [cs.title, cs.slug, cs.industry, cs.challenge, cs.approach, cs.result, cs.metrics]
        );
      }
    }

    // Seed insights (clear and reseed)
    await client.query("DELETE FROM insights");
    {
      const insights = [
        { title: '5 Cash Flow Mistakes That Kill Small Businesses', slug: 'cash-flow-mistakes', summary: 'Most small businesses that fail are actually profitable on paper. The real killer is cash flow. Here are the 5 most common mistakes and how to avoid them.', content: 'Cash flow is the lifeblood of every small business, yet most owners focus almost exclusively on revenue and profit — ignoring the timing of when money actually moves.\n\n## Mistake #1: Confusing Profit with Cash\n\nYour P&L might show a healthy profit, but if your receivables are at 60 days and your payables are at 30, you have a structural cash gap that can sink you.\n\n## Mistake #2: No Cash Flow Forecast\n\nMost small business owners check their bank balance and guess. A weekly cash flow forecast takes the guesswork out and gives you 4-8 weeks of visibility.\n\n## Mistake #3: Growing Too Fast Without a Plan\n\nGrowth eats cash. Every new client, hire, or location requires cash upfront before revenue comes in. Without a plan, growth can actually make your cash situation worse.\n\n## Mistake #4: Ignoring Seasonality\n\nIf your business has seasonal patterns — and most do — you need to build cash reserves during strong months to survive the slow ones.\n\n## Mistake #5: No Cash Buffer\n\nA healthy business should have 2-3 months of operating expenses in reserve. Without this buffer, one late payment or unexpected expense can create a crisis.\n\n## The Fix\n\nImplement weekly cash flow forecasting, understand your cash conversion cycle, and plan for growth before you commit to it.', category: 'Cash Flow', domain: 'financial-management', published: true, featured: true },
        { title: 'When Should a Small Business Hire a Fractional CFO?', slug: 'fractional-cfo-guide', summary: 'You know you need financial expertise, but a full-time CFO costs $200K+. Here is how to know when a fractional CFO is the right move.', content: 'Most small businesses outgrow their bookkeeper long before they can afford a full-time CFO. That gap is where expensive mistakes happen.\n\n## Signs You Need More Than a Bookkeeper\n\n- You are making major financial decisions based on gut feeling\n- You cannot answer "how much cash will we have in 6 weeks?"\n- Your financial statements are just for tax time, not decision-making\n- You are growing but profits are not keeping up\n\n## What a Fractional CFO Does\n\n1. **Financial statement analysis** — turning your numbers into actionable insights\n2. **Cash flow forecasting** — weekly and monthly projections\n3. **Budget planning** — structured annual budgets aligned with your goals\n4. **Scenario modeling** — data-driven analysis for major decisions\n5. **KPI tracking** — knowing which metrics actually drive your business\n\n## The Cost Comparison\n\nFull-time CFO: $200K-$400K+. Fractional CFO: $2K-$8K/month. You get 80% of the value at 10-20% of the cost.', category: 'Advisory', domain: 'business-growth', published: true, featured: true },
        { title: 'How to Read Your Financial Statements Like a CEO', slug: 'read-financial-statements', summary: 'Your financial statements tell a story about your business. Here is how to read them beyond the bottom line.', content: 'Most small business owners glance at their P&L, check if they made money, and move on. But your financial statements contain insights that can transform how you run your business.\n\n## Profit & Loss (Income Statement)\n- **Gross margin** tells you if your pricing and direct costs are healthy\n- **Operating margin** tells you if your overhead is sustainable\n- **Trends matter more than snapshots** — compare month over month\n\n## Balance Sheet\n- **Current ratio** — can you pay your bills?\n- **Working capital** — the cash you need to operate day-to-day\n- **Debt levels** — are you over-leveraged?\n\n## Cash Flow Statement\n- **Operating cash flow** — is your core business generating cash?\n- **Investing cash flow** — what are you spending on growth?\n- **Financing cash flow** — how are you funding the business?\n\n## Key Metrics to Track Monthly\n1. Gross margin percentage\n2. Net profit margin\n3. Current ratio\n4. Days sales outstanding (DSO)\n5. Cash runway', category: 'Financial Literacy', domain: 'financial-management', published: true, featured: false },
        { title: 'The Small Business Owner Guide to Annual Budget Planning', slug: 'annual-budget-guide', summary: 'A budget is not just a spreadsheet — it is your financial roadmap. Here is a practical guide to building one that actually works.', content: '## Why Most Small Business Budgets Fail\n\nThey are either too complicated (and get abandoned) or too simple (and are useless). A good budget is a living document that guides decisions.\n\n## Step 1: Start with Revenue\nProject revenue conservatively. Use last year as a baseline, then adjust for known changes — new clients, lost clients, price changes, seasonal patterns.\n\n## Step 2: Fixed Costs\nList every fixed expense: rent, salaries, insurance, subscriptions, loan payments. These do not change with revenue and must be covered no matter what.\n\n## Step 3: Variable Costs\nThese move with revenue: materials, commissions, shipping, credit card fees. Express them as a percentage of revenue.\n\n## Step 4: One-Time Investments\nPlanned hires, equipment purchases, marketing campaigns. Budget these separately with clear timing.\n\n## Step 5: Monthly Review\nCompare actual vs. budget every month. Variance analysis is where the real value lives — it tells you where reality differs from your plan and why.', category: 'Budgeting', domain: 'financial-management', published: true, featured: false },
        { title: 'Understanding Gross Margin: The Most Important Number in Your Business', slug: 'understanding-gross-margin', summary: 'Gross margin is the single most important indicator of your business health. Here is what it means and how to improve it.', content: '## What Is Gross Margin?\n\nGross margin = (Revenue - Cost of Goods Sold) / Revenue. It tells you how much money you keep from each dollar of revenue after paying for the direct costs of delivering your product or service.\n\n## Why It Matters So Much\n\nEverything else — rent, salaries, marketing, profit — comes out of your gross margin. If your gross margin is too low, no amount of cost-cutting on overhead will save you.\n\n## Benchmarks by Industry\n- Restaurants: 60-70%\n- Retail: 40-60%\n- Professional services: 70-85%\n- Construction: 25-40%\n- Manufacturing: 30-50%\n- SaaS: 70-85%\n\n## How to Improve It\n1. Raise prices (even 5% can have a dramatic impact)\n2. Reduce direct costs (negotiate with suppliers)\n3. Cut unprofitable products or services\n4. Improve operational efficiency\n5. Shift mix toward higher-margin offerings', category: 'Financial Literacy', domain: 'financial-management', published: true, featured: true },
        { title: 'How to Forecast Cash Flow for Your Small Business', slug: 'how-to-forecast-cash-flow', summary: 'A step-by-step guide to building a weekly cash flow forecast that gives you visibility and control over your finances.', content: '## The 13-Week Cash Flow Forecast\n\nThis is the gold standard for small business cash flow management. It gives you a rolling 3-month view of exactly where your cash is going.\n\n## How to Build It\n\n### Step 1: Starting Cash\nYour current bank balance. Simple.\n\n### Step 2: Cash In\nList every expected cash receipt by week: customer payments, recurring revenue, deposits, refunds, other income.\n\n### Step 3: Cash Out\nList every expected payment by week: payroll, rent, vendors, loan payments, taxes, subscriptions.\n\n### Step 4: Net Cash Flow\nCash In minus Cash Out for each week. This shows you which weeks are positive and which are negative.\n\n### Step 5: Running Balance\nStarting cash plus cumulative net cash flow. This is your projected bank balance for every week.\n\n## Update It Weekly\nSpend 30 minutes every Monday updating actuals and adjusting projections. This single habit will transform your financial confidence.', category: 'Cash Flow', domain: 'financial-management', published: true, featured: false },
        { title: 'Pricing Strategy for Small Businesses: Stop Leaving Money on the Table', slug: 'pricing-strategy-guide', summary: 'Most small businesses underprice their services. Here is how to set prices based on data, not fear.', content: '## The Pricing Problem\n\nMost small business owners set prices based on what competitors charge or what feels right. Both approaches leave money on the table.\n\n## Cost-Plus Pricing\nCalculate your true cost (including overhead allocation), then add your desired margin. This is the floor — never price below this.\n\n## Value-Based Pricing\nWhat is the outcome worth to your customer? A $500 service that saves a client $10,000 is a bargain at twice the price.\n\n## The Price Increase Test\nRaise prices 10% for new customers. If you lose fewer than 10% of prospects, the increase is profitable. Most businesses find they lose far fewer than expected.\n\n## Know Your Numbers\n- What is your fully-loaded cost per unit/hour/project?\n- What is your current margin?\n- What would a 5%, 10%, 15% increase do to your bottom line?\n- What is your price elasticity (how sensitive are customers to price changes)?', category: 'Strategy', domain: 'business-growth', published: true, featured: false },
        { title: 'The Real Cost of a Bad Hire: A Financial Analysis', slug: 'cost-of-bad-hire', summary: 'A bad hire costs 3-5x their salary when you add up all the hidden expenses. Here is how to model hiring decisions financially.', content: '## The True Cost\n\nWhen you factor in recruiting, training, lost productivity, management time, severance, and rehiring, a bad hire at $50K salary can cost $150K-$250K.\n\n## Model Before You Hire\n\nBefore making any hire, build a simple financial model:\n1. **Fully loaded cost**: salary + benefits + taxes + equipment + training\n2. **Revenue impact**: how much additional revenue will this person generate or enable?\n3. **Break-even timeline**: when does the hire start paying for itself?\n4. **Cash flow impact**: can you afford 3-6 months of cost before the revenue materializes?\n\n## The Contractor Alternative\nFor many small businesses, starting with a contractor is financially smarter. You test the role, avoid benefits costs, and can scale up or down quickly.\n\n## Key Takeaway\nEvery hire is a financial decision. Treat it like any other investment — model the numbers before you commit.', category: 'Strategy', domain: 'business-growth', published: true, featured: false },
        { title: 'Working Capital: The Hidden Engine of Your Business', slug: 'working-capital-explained', summary: 'Working capital is the cash your business needs to operate day-to-day. Here is how to manage it effectively.', content: '## What Is Working Capital?\n\nWorking capital = Current Assets - Current Liabilities. It is the money available to fund your daily operations.\n\n## Why It Matters\n\nYou can be profitable and still run out of working capital. This happens when:\n- Customers pay slowly (high receivables)\n- You carry too much inventory\n- You pay vendors too quickly\n- You are growing fast and funding that growth from operations\n\n## How to Improve It\n\n1. **Speed up collections**: Invoice immediately, offer early payment discounts, follow up consistently\n2. **Manage inventory**: Only stock what you need. Dead inventory is dead cash.\n3. **Negotiate payables**: Ask vendors for net-45 or net-60 terms instead of net-30\n4. **Monitor weekly**: Track your working capital ratio every week, not just at month-end\n\n## The Working Capital Cycle\nUnderstand how long it takes for a dollar spent to come back as revenue. Shorten this cycle and you free up cash for growth.', category: 'Cash Flow', domain: 'financial-management', published: true, featured: false },
        { title: 'Scenario Modeling: How to Make Big Decisions with Confidence', slug: 'scenario-modeling-guide', summary: 'Should you hire? Open a new location? Buy equipment? Scenario modeling gives you the data to decide with confidence.', content: '## What Is Scenario Modeling?\n\nIt is building financial projections for different versions of the future — best case, worst case, and most likely case.\n\n## When to Use It\n\n- Opening a new location\n- Making a major equipment purchase\n- Hiring key employees\n- Raising prices\n- Taking on debt\n- Launching a new product or service\n\n## How to Build a Scenario Model\n\n### Step 1: Define the Decision\nWhat exactly are you deciding? Be specific.\n\n### Step 2: Identify Variables\nWhat factors affect the outcome? Revenue, costs, timing, market conditions.\n\n### Step 3: Build Three Scenarios\n- **Conservative**: pessimistic assumptions\n- **Base case**: most likely assumptions\n- **Optimistic**: best-case assumptions\n\n### Step 4: Model Cash Impact\nFor each scenario, project the cash flow impact over 12-24 months.\n\n### Step 5: Identify Break-Even\nAt what point does the investment pay for itself in each scenario?\n\n## The Power of Scenario Modeling\nYou stop asking "should I?" and start asking "under what conditions does this work?" That is a much more powerful question.', category: 'Advisory', domain: 'financial-management', published: true, featured: true },
        { title: 'Tax Planning Strategies Every Small Business Should Know', slug: 'tax-planning-strategies', summary: 'Proactive tax planning throughout the year can save you thousands. Here are strategies that actually work for small businesses.', content: '## Stop Doing Taxes Once a Year\n\nThe biggest tax mistake small businesses make is only thinking about taxes in March. Proactive quarterly planning saves real money.\n\n## Key Strategies\n\n### 1. Maximize Deductions\nTrack every business expense meticulously. Common missed deductions: home office, vehicle use, professional development, software subscriptions.\n\n### 2. Retirement Contributions\nSEP-IRA, Solo 401(k), or SIMPLE IRA contributions reduce taxable income significantly. A SEP-IRA alone allows up to 25% of net self-employment income.\n\n### 3. Entity Structure Review\nAre you structured as the right entity type? An LLC taxed as an S-Corp can save thousands in self-employment taxes once you hit $80K+ in profit.\n\n### 4. Quarterly Estimated Payments\nPay quarterly estimates to avoid underpayment penalties. Better yet, use these as a forcing function to review your finances every quarter.\n\n### 5. Year-End Planning\nIn Q4, estimate your annual income and look for opportunities to accelerate deductions or defer income.', category: 'Tax', domain: 'financial-management', published: true, featured: false },
        { title: 'Debt vs. Equity: How to Fund Your Business Growth', slug: 'debt-vs-equity-funding', summary: 'Growing businesses need capital. Here is how to decide between debt, equity, or bootstrapping based on your financial situation.', content: '## The Three Paths\n\n### Bootstrapping (Self-Funded)\n**Best for**: businesses with strong cash flow that can fund growth from operations.\n**Pros**: no debt, no dilution, full control.\n**Cons**: slower growth, personal financial risk.\n\n### Debt (Loans, Lines of Credit)\n**Best for**: businesses with predictable revenue and assets for collateral.\n**Pros**: you keep 100% ownership, interest is tax-deductible.\n**Cons**: repayment obligations regardless of performance, collateral requirements.\n\n### Equity (Investors)\n**Best for**: high-growth businesses that need significant capital and can offer attractive returns.\n**Pros**: no repayment obligation, strategic partners.\n**Cons**: dilution, loss of some control, investor expectations.\n\n## The Financial Analysis\n\nBefore choosing, model:\n1. How much capital do you actually need?\n2. What is the expected ROI on this capital?\n3. Can your cash flow support debt service?\n4. What is the cost of capital for each option?\n5. What is the impact on your ownership and control?', category: 'Strategy', domain: 'business-growth', published: true, featured: false },
        { title: 'Monthly Financial Review: A 30-Minute Routine That Changes Everything', slug: 'monthly-financial-review', summary: 'The most successful small business owners spend 30 minutes each month reviewing their numbers. Here is exactly what to look at.', content: '## The Monthly Review Checklist\n\nBlock 30 minutes on the first week of each month. Here is your agenda:\n\n### 1. P&L Review (10 minutes)\n- Revenue vs. last month and vs. budget\n- Gross margin — is it holding steady?\n- Any expense line items that jumped unexpectedly?\n- Net profit margin trend\n\n### 2. Cash Flow Check (10 minutes)\n- Current bank balance\n- Outstanding receivables (who owes you?)\n- Upcoming payables (what is due this month?)\n- Cash runway — how many months can you operate at current burn rate?\n\n### 3. KPI Dashboard (5 minutes)\n- Customer acquisition cost\n- Average revenue per customer\n- Customer retention rate\n- Employee productivity metrics\n\n### 4. Action Items (5 minutes)\n- What needs to change based on what you just saw?\n- Are there invoices to follow up on?\n- Any spending that needs to be addressed?\n\n## Why This Works\nConsistency beats intensity. A 30-minute monthly review gives you more financial clarity than a 3-day annual planning retreat.', category: 'Financial Literacy', domain: 'financial-management', published: true, featured: false },
        { title: 'How to Prepare Your Business for a Recession', slug: 'recession-preparation', summary: 'You cannot predict a recession, but you can prepare for one. Here are the financial steps to take now.', content: '## Build a War Chest\n\nThe businesses that thrive in recessions are the ones with cash reserves. Aim for 3-6 months of operating expenses in reserve.\n\n## Stress-Test Your Cash Flow\n\nModel what happens if revenue drops 20%, 30%, 40%. At each level:\n- Can you cover fixed costs?\n- What expenses can be cut quickly?\n- Which customers are most at risk?\n\n## Reduce Fixed Costs\nConvert fixed costs to variable where possible. Renegotiate leases, switch to performance-based compensation, use contractors instead of full-time hires.\n\n## Strengthen Customer Relationships\nYour existing customers are your most valuable asset in a downturn. Invest in retention — it is cheaper than acquisition.\n\n## Diversify Revenue\nIf 50% of your revenue comes from one client or one product, you are vulnerable. Diversify now while times are good.\n\n## Get Your Financial House in Order\nRecession or not, businesses with clear financial visibility, accurate forecasts, and strong cash management always outperform those without.', category: 'Strategy', domain: 'business-growth', published: true, featured: true },
        { title: 'Accounts Receivable: How to Get Paid Faster', slug: 'get-paid-faster', summary: 'Slow-paying customers are one of the top cash flow killers for small businesses. Here is how to fix it.', content: '## The AR Problem\n\nThe average small business has $50K-$200K tied up in receivables at any given time. That is cash you cannot use for operations, payroll, or growth.\n\n## 7 Ways to Speed Up Collections\n\n1. **Invoice immediately**: Do not wait until month-end. Invoice the day you deliver.\n2. **Make it easy to pay**: Accept credit cards, ACH, and online payments.\n3. **Offer early payment discounts**: 2/10 net 30 (2% discount for paying within 10 days).\n4. **Require deposits**: For large projects, get 25-50% upfront.\n5. **Follow up consistently**: Call on day 31, not day 60.\n6. **Track aging weekly**: Know exactly who owes what and for how long.\n7. **Fire bad-paying customers**: If someone consistently pays 90+ days late, they are costing you money.\n\n## Know Your DSO\nDays Sales Outstanding = (Accounts Receivable / Revenue) x Days. Track this monthly. If it is creeping up, you have a collection problem.', category: 'Cash Flow', domain: 'financial-management', published: true, featured: false },
      ];

      for (const ins of insights) {
        await client.query(
          "INSERT INTO insights (title, slug, summary, content, category, domain, published, featured) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)",
          [ins.title, ins.slug, ins.summary, ins.content, ins.category, ins.domain, ins.published, ins.featured]
        );
      }
    }

    // Seed testimonials (clear and reseed)
    await client.query("DELETE FROM testimonials");
    {
      const testimonials = [
        { name: 'Maria Lopez', title: 'Owner', company: 'Bella Rosa Restaurant Group', quote: 'Before Akarsu Advisory, I was checking my bank account every morning hoping we had enough cash. Now I have a weekly forecast and I actually understand my numbers. They changed how I run my business.' },
        { name: 'James Peterson', title: 'Founder', company: 'Peterson Construction', quote: 'They helped us see which jobs were actually making money and which were draining us. The scenario modeling for our equipment purchase saved us from a $200K mistake.' },
        { name: 'Rachel Kim', title: 'CEO', company: 'BrightPath Dental', quote: 'Opening our second location felt overwhelming until Akarsu built the financial model. We knew exactly what we needed to hit breakeven and we got there 2 months early.' },
        { name: 'David Okafor', title: 'Owner', company: 'NorthStar E-Commerce', quote: 'I thought we were profitable on every product. Turns out 30% of our SKUs were losing money after all costs. Akarsu helped us see it and fix it — our margins doubled in 6 months.' },
        { name: 'Sarah Mitchell', title: 'Managing Partner', company: 'Mitchell & Associates Law Firm', quote: 'We had no idea how much revenue each partner was actually generating. Akarsu built us a financial model that brought total transparency. Partner disputes about compensation disappeared overnight.' },
        { name: 'Tom Richardson', title: 'Owner', company: 'Richardson Trucking', quote: 'I was about to buy 5 new trucks. Akarsu showed me the numbers — 3 trucks was the right move. They saved me $400K and the 3 trucks paid for themselves in 14 months.' },
        { name: 'Angela Chen', title: 'Founder', company: 'Glow Beauty Studio', quote: 'The membership revenue model they helped us build completely changed our business. We went from unpredictable monthly income to $32K in recurring revenue. I can finally plan ahead.' },
        { name: 'Robert Williams', title: 'CEO', company: 'FreshStart SaaS', quote: 'We were burning cash and thought we had 18 months of runway. Akarsu found $8K/month in waste and extended our runway to 28 months. We hit profitability before we even needed to fundraise.' },
        { name: 'Linda Martinez', title: 'Owner', company: 'Martinez Family Farm', quote: 'The seasonal cash flow planning they did for us was a game changer. For the first time in 20 years of farming, I did not have to take a personal loan to get through winter.' },
        { name: 'Kevin O\'Brien', title: 'Franchise Owner', company: 'Quick Bites (6 locations)', quote: 'I had 6 locations and no idea which ones were profitable. Akarsu consolidated everything into one dashboard. We fixed 2 underperforming locations and profitability jumped 18%.' },
        { name: 'Diana Patel', title: 'Owner', company: 'Comfort Zone HVAC', quote: 'Winter used to terrify me financially. Now I have maintenance contracts generating revenue year-round and a $150K cash reserve. Akarsu helped me build a real business, not just a seasonal one.' },
        { name: 'Marcus Johnson', title: 'Owner', company: 'Johnson Auto Care', quote: 'They showed me I was undercharging by 15% and losing customers at only a 3% rate when I raised prices. My profit margin went from 6% to 19%. I wish I had called them years ago.' },
        { name: 'Patricia Nguyen', title: 'Executive Director', company: 'Youth Forward Foundation', quote: 'As a nonprofit, we were always scrambling between grant disbursements. Akarsu helped us build a reserve fund and plan around grant cycles. We have not missed a program deadline since.' },
        { name: 'Steven Hart', title: 'Owner', company: 'Hart Custom Furniture', quote: 'Our margins were shrinking and I could not figure out why. Akarsu found $180K in annual material waste we did not know about. Margins went from 12% back to 22% in 8 months.' },
        { name: 'Jennifer Brooks', title: 'Investor', company: 'Brooks Property Group', quote: 'I had 12 rental properties but no clear picture of per-property profitability. Akarsu built a portfolio model that showed me which to keep and which to sell. Cash flow is up 35%.' },
      ];

      for (const t of testimonials) {
        await client.query(
          "INSERT INTO testimonials (name, title, company, quote) VALUES ($1,$2,$3,$4)",
          [t.name, t.title, t.company, t.quote]
        );
      }
    }

    // Seed consultations
    const conCount = await client.query("SELECT COUNT(*) FROM consultations");
    if (parseInt(conCount.rows[0].count) === 0) {
      const consultations = [
        { name: 'Mike Johnson', email: 'mike@johnsonconstruction.com', company: 'Johnson Construction LLC', phone: '312-555-0101', service_interest: 'Weekly Cash Flow Forecasting', message: 'We are a general contractor doing about $3M in revenue. Cash flow is our biggest headache — we never know when client payments will come in. Need help forecasting.', preferred_date: '2026-04-15', preferred_time: 'Morning (9am-12pm)', status: 'pending' },
        { name: 'Sarah Chen', email: 'sarah@brightsideretail.com', company: 'Brightside Retail', phone: '312-555-0102', service_interest: 'Financial Statement Review & Analysis', message: 'We have 3 retail locations and I feel like we are leaving money on the table but I cannot figure out where. Need someone to review our financials and tell us what we are missing.', preferred_date: '2026-04-16', preferred_time: 'Afternoon (12pm-5pm)', status: 'contacted' },
        { name: 'Robert Garcia', email: 'rob@garcialaw.com', company: 'Garcia & Partners Law', phone: '312-555-0103', service_interest: 'Annual Budget Planning', message: 'Our law firm has 8 attorneys and we have never had a formal budget. Partners argue about spending constantly. We need structure.', preferred_date: '2026-04-17', preferred_time: 'Morning (9am-12pm)', status: 'pending' },
        { name: 'Lisa Thompson', email: 'lisa@freshbitescatering.com', company: 'Fresh Bites Catering', phone: '312-555-0104', service_interest: 'Monthly P&L Forecasting', message: 'My catering business is growing fast but profits are not keeping up. I need to understand our margins better and forecast where we are headed.', preferred_date: '2026-04-18', preferred_time: 'Afternoon (12pm-5pm)', status: 'scheduled' },
        { name: 'Ahmed Hassan', email: 'ahmed@hassantech.io', company: 'Hassan Tech Solutions', phone: '312-555-0105', service_interest: 'Scenario Modeling', message: 'We are a SaaS startup considering hiring 5 more engineers. Need to model whether we can afford it and how it impacts our runway.', preferred_date: '2026-04-19', preferred_time: 'Morning (9am-12pm)', status: 'pending' },
        { name: 'Jennifer Wright', email: 'jen@wrightdental.com', company: 'Wright Family Dental', phone: '312-555-0106', service_interest: 'Scenario Modeling', message: 'Thinking about opening a second dental office location. Need financial modeling to know if we can afford it and when we would break even.', preferred_date: '2026-04-20', preferred_time: 'Evening (5pm-8pm)', status: 'contacted' },
        { name: 'Carlos Rivera', email: 'carlos@riveratrucking.com', company: 'Rivera Trucking Co', phone: '312-555-0107', service_interest: 'Weekly Cash Flow Forecasting', message: 'We have 20 trucks and our customers pay net-60. Fuel costs are killing us and we never have enough cash. Desperately need forecasting help.', preferred_date: '2026-04-21', preferred_time: 'Morning (9am-12pm)', status: 'pending' },
        { name: 'Emily Park', email: 'emily@glowskincare.com', company: 'Glow Skincare Studio', phone: '312-555-0108', service_interest: 'Financial Statement Review & Analysis', message: 'I have been running my salon for 3 years and have no idea if I am actually making money. My bookkeeper gives me reports but I do not understand them.', preferred_date: '2026-04-22', preferred_time: 'Afternoon (12pm-5pm)', status: 'completed' },
        { name: 'Daniel Foster', email: 'dan@fosterfarming.com', company: 'Foster Family Farm', phone: '312-555-0109', service_interest: 'Annual Budget Planning', message: 'We need help planning our annual budget around growing seasons. Every winter we struggle financially and I am tired of taking personal loans.', preferred_date: '2026-04-23', preferred_time: 'Morning (9am-12pm)', status: 'pending' },
        { name: 'Maria Gonzalez', email: 'maria@tacofiesta.com', company: 'Taco Fiesta (3 locations)', phone: '312-555-0110', service_interest: 'Fractional CFO Services', message: 'I have 3 taco restaurants doing about $2M combined but I know nothing about finance. I need someone who can be my CFO on a part-time basis.', preferred_date: '2026-04-24', preferred_time: 'Morning (9am-12pm)', status: 'scheduled' },
        { name: 'Kevin Brown', email: 'kevin@brownplumbing.com', company: 'Brown Plumbing & HVAC', phone: '312-555-0111', service_interest: 'Break-Even Analysis', message: 'Want to add HVAC services to our plumbing business. Need to know how many jobs we need per month to make it worthwhile.', preferred_date: '2026-04-25', preferred_time: 'Afternoon (12pm-5pm)', status: 'pending' },
        { name: 'Nicole Adams', email: 'nicole@adamsaccounting.com', company: 'Adams Accounting Group', phone: '312-555-0112', service_interest: 'KPI Dashboard & Reporting', message: 'We are an accounting firm that ironically does not track our own KPIs well. Want to build a proper dashboard for partner performance.', preferred_date: '2026-04-26', preferred_time: 'Morning (9am-12pm)', status: 'contacted' },
        { name: 'Peter Lee', email: 'peter@leeproperties.com', company: 'Lee Property Management', phone: '312-555-0113', service_interest: 'Financial Statement Review & Analysis', message: 'I manage 15 rental properties and I do not know the true cash flow per property. Need a detailed financial review of my portfolio.', preferred_date: '2026-04-27', preferred_time: 'Evening (5pm-8pm)', status: 'pending' },
        { name: 'Amanda White', email: 'amanda@youthforward.org', company: 'Youth Forward Foundation', phone: '312-555-0114', service_interest: 'Weekly Cash Flow Forecasting', message: 'Our nonprofit runs out of cash between grant disbursements. We need help forecasting and managing our cash around grant cycles.', preferred_date: '2026-04-28', preferred_time: 'Morning (9am-12pm)', status: 'pending' },
        { name: 'Jason Martinez', email: 'jason@quickbites.com', company: 'Quick Bites Franchise (4 units)', phone: '312-555-0115', service_interest: 'Monthly P&L Forecasting', message: 'I own 4 franchise locations but only 2 seem profitable. Need monthly P&L forecasting per location so I can figure out what is going wrong.', preferred_date: '2026-04-29', preferred_time: 'Afternoon (12pm-5pm)', status: 'scheduled' },
      ];
      for (const c of consultations) {
        await client.query(
          "INSERT INTO consultations (name, email, company, phone, service_interest, message, preferred_date, preferred_time, status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)",
          [c.name, c.email, c.company, c.phone, c.service_interest, c.message, c.preferred_date, c.preferred_time, c.status]
        );
      }
    }

    // Seed contacts
    const ctCount = await client.query("SELECT COUNT(*) FROM contacts");
    if (parseInt(ctCount.rows[0].count) === 0) {
      const contacts = [
        { name: 'Tom Richardson', email: 'tom@richardsonmfg.com', company: 'Richardson Manufacturing', phone: '312-555-0201', subject: 'Question about pricing', message: 'Hi, I saw your website and I am interested in financial statement review services. Can you tell me about your pricing structure? We are a small manufacturing company doing about $4M in revenue.', status: 'new' },
        { name: 'Diane Patel', email: 'diane@patelfitness.com', company: 'Patel Fitness Studios', phone: '312-555-0202', subject: 'Membership revenue modeling', message: 'I own 2 fitness studios and want to transition from drop-in to membership model. Do you help with revenue modeling for this kind of change?', status: 'read' },
        { name: 'Chris O\'Brien', email: 'chris@obrienauto.com', company: 'O\'Brien Auto Repair', phone: '312-555-0203', subject: 'Pricing analysis help', message: 'I think we are undercharging for our services but I am afraid to raise prices and lose customers. Can you help us analyze our pricing?', status: 'new' },
        { name: 'Sandra Kim', email: 'sandra@kimcleaning.com', company: 'Kim Cleaning Services', phone: '312-555-0204', subject: 'Growing from solo to team', message: 'I run a cleaning business by myself doing $150K/year. I want to hire employees and grow but I do not know if the numbers work. Can you help me model this?', status: 'replied' },
        { name: 'Mark Davis', email: 'mark@davislandscaping.com', company: 'Davis Landscaping', phone: '312-555-0205', subject: 'Seasonal cash flow problems', message: 'Every winter we nearly go bankrupt. Summer is great but we cannot seem to save enough to get through the off-season. Is this something you help with?', status: 'new' },
        { name: 'Angela Torres', email: 'angela@torresdesign.com', company: 'Torres Design Agency', phone: '312-555-0206', subject: 'Retainer vs project pricing', message: 'My design agency mostly does project work but I want to move to retainers for more predictable income. Can you help us model the financial impact?', status: 'new' },
        { name: 'Ryan Clark', email: 'ryan@clarkelectric.com', company: 'Clark Electrical', phone: '312-555-0207', subject: 'Equipment financing question', message: 'We need to buy a new service van and diagnostic equipment (~$80K total). Should we buy, lease, or finance? I do not know how to evaluate the options.', status: 'read' },
        { name: 'Melissa Wang', email: 'melissa@wangbakery.com', company: 'Wang\'s Artisan Bakery', phone: '312-555-0208', subject: 'Opening second location', message: 'Our bakery is doing well and we want to open a second location. We have about $50K saved. Is that enough? How do we figure out if we can afford it?', status: 'new' },
        { name: 'Greg Taylor', email: 'greg@taylorroofing.com', company: 'Taylor Roofing Co', phone: '312-555-0209', subject: 'Job costing help', message: 'We are winning bids but not making money on them. I think our job costing is off but I do not know where. Can your team help us figure it out?', status: 'new' },
        { name: 'Laura Smith', email: 'laura@smithvet.com', company: 'Smith Veterinary Clinic', phone: '312-555-0210', subject: 'Partnership buyout modeling', message: 'My business partner wants to retire and I need to buy them out. Can you help me model the financial impact and figure out a fair price?', status: 'replied' },
        { name: 'Brian Johnson', email: 'brian@bjconsulting.com', company: 'BJ Consulting', phone: '312-555-0211', subject: 'Monthly retainer question', message: 'How does your fractional CFO service work? Is it a monthly retainer? How many hours per month? I am a solo consultant doing about $300K/year.', status: 'new' },
        { name: 'Patricia Nguyen', email: 'patricia@greenthumbnursery.com', company: 'Green Thumb Nursery', phone: '312-555-0212', subject: 'Inventory management', message: 'We are a garden nursery and our inventory (plants) literally dies if we buy too much. We need help with inventory analysis and cash flow planning around seasonal demand.', status: 'new' },
        { name: 'Steven Hart', email: 'steven@hartfurniture.com', company: 'Hart Custom Furniture', phone: '312-555-0213', subject: 'Margin analysis request', message: 'Our custom furniture margins have been shrinking for 2 years. Revenue is up but profit is down. We need someone to dig into our COGS and figure out what is happening.', status: 'read' },
        { name: 'Rachel Green', email: 'rachel@greenevents.com', company: 'Green Events Planning', phone: '312-555-0214', subject: 'Cash flow timing issues', message: 'In event planning, we pay vendors upfront but do not get full payment from clients until after the event. This creates huge cash flow gaps. How can you help?', status: 'new' },
        { name: 'Alex Turner', email: 'alex@turnertech.io', company: 'Turner Tech Startup', phone: '312-555-0215', subject: 'Fundraising financial model', message: 'We are preparing to raise a seed round and need a proper financial model. Our current projections are basically guesses. Can you help us build something investors will trust?', status: 'new' },
      ];
      for (const c of contacts) {
        await client.query(
          "INSERT INTO contacts (name, email, company, phone, subject, message, status) VALUES ($1,$2,$3,$4,$5,$6,$7)",
          [c.name, c.email, c.company, c.phone, c.subject, c.message, c.status]
        );
      }
    }

    console.log('Database seeded successfully');
  } catch (err) {
    console.error('Seed error:', err.message);
  } finally {
    client.release();
  }
}

if (require.main === module) seed();
module.exports = seed;
