'use strict';
const crypto=require('crypto');
const states={submitted:['qualification_review','withdrawn'],qualification_review:['qualified','needs_information','disqualified'],needs_information:['qualification_review','withdrawn'],qualified:['discovery_requested'],discovery_requested:['discovery_scheduled','provider_error'],provider_error:['discovery_requested','proposal_generation_queued','proposal_delivery_queued','kickoff_queued','withdrawn'],discovery_scheduled:['discovery_completed','no_show'],no_show:['discovery_requested','withdrawn'],discovery_completed:['proposal_review'],proposal_review:['proposal_approved','proposal_rejected'],proposal_rejected:['proposal_review','withdrawn'],proposal_approved:['proposal_generation_queued'],proposal_generation_queued:['proposal_ready','provider_error'],proposal_ready:['proposal_delivery_queued'],proposal_delivery_queued:['proposal_sent','provider_error'],proposal_sent:['accepted','declined'],accepted:['kickoff_queued'],kickoff_queued:['active','provider_error'],active:['closed'],declined:[],disqualified:[],withdrawn:[],closed:[]};
const grants={analyst:new Set(['submitted:qualification_review','qualification_review:qualified','qualification_review:needs_information','qualification_review:disqualified','needs_information:qualification_review']),advisor:new Set(['qualified:discovery_requested','provider_error:discovery_requested','discovery_scheduled:discovery_completed','discovery_scheduled:no_show','no_show:discovery_requested','discovery_completed:proposal_review','proposal_rejected:proposal_review','proposal_approved:proposal_generation_queued','provider_error:proposal_generation_queued','proposal_ready:proposal_delivery_queued','provider_error:proposal_delivery_queued','accepted:kickoff_queued','provider_error:kickoff_queued','active:closed']),manager:new Set(['proposal_review:proposal_approved','proposal_review:proposal_rejected','submitted:withdrawn','needs_information:withdrawn','no_show:withdrawn','proposal_rejected:withdrawn']),admin:new Set(['*']),provider:new Set(['discovery_requested:discovery_scheduled','discovery_requested:provider_error','proposal_generation_queued:proposal_ready','proposal_generation_queued:provider_error','proposal_delivery_queued:proposal_sent','proposal_delivery_queued:provider_error','kickoff_queued:active','kickoff_queued:provider_error']),client:new Set(['proposal_sent:accepted','proposal_sent:declined'])};
function canonical(v){if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;return JSON.stringify(v)}const digest=v=>crypto.createHash('sha256').update(canonical(v)).digest('hex');
function clean(v,n,m=500){if(typeof v!=='string'||!v.trim()||v.length>m)throw new Error(`${n} required`);return v.trim()}function noSecrets(v){if(/password|secret|token|api.?key|authorization/i.test(canonical(v)))throw new Error('credentials forbidden')}
function intake(v){noSecrets(v);const x={name:clean(v?.name,'name',120),email:clean(v?.email,'email',254).toLowerCase(),company:clean(v?.company,'company',200),phone:clean(v?.phone,'phone',40),service:clean(v?.service,'service',120),challenge:clean(v?.challenge,'challenge',3000),employeeBand:clean(v?.employeeBand,'employeeBand',40),industry:clean(v?.industry,'industry',120),budgetBand:clean(v?.budgetBand,'budgetBand',40),timeline:clean(v?.timeline,'timeline',40),consentToContact:v?.consentToContact===true};if(!/^\S+@\S+\.\S+$/.test(x.email))throw new Error('email invalid');if(!['financial_review','budget_forecast','cash_flow','scenario_modeling','operations_advisory'].includes(x.service))throw new Error('service invalid');if(!['under_5k','5k_15k','15k_plus','undecided'].includes(x.budgetBand)||!['within_30_days','1_3_months','later'].includes(x.timeline))throw new Error('budget or timeline invalid');return x}
function qualify(v){const missing=[];if(!v.consentToContact)missing.push('contact_consent');if(v.challenge.length<50)missing.push('detailed_challenge');if(v.budgetBand==='undecided')missing.push('budget');return{eligible:missing.length===0,missing,requiresHuman:true}}
function transition(from,to,actor,owner){if(!states[from]?.includes(to))throw new Error(`invalid transition ${from} -> ${to}`);const g=grants[actor.role];if(!g||(!g.has('*')&&!g.has(`${from}:${to}`)))throw new Error('role cannot perform transition');if(to==='proposal_approved'&&String(actor.id)===String(owner))throw new Error('independent proposal approver required');return true}
function proposal(v){noSecrets(v);const deliverables=Array.isArray(v?.deliverables)?v.deliverables:[],milestones=Array.isArray(v?.milestones)?v.milestones:[];if(!deliverables.length||deliverables.length>20||!milestones.length||milestones.length>20)throw new Error('deliverables and milestones required');const p={title:clean(v.title,'title',200),scope:clean(v.scope,'scope',4000),currency:clean(v.currency,'currency',3).toUpperCase(),validUntil:new Date(v.validUntil).toISOString(),deliverables:deliverables.map(x=>({name:clean(x.name,'deliverable name',200),acceptanceCriterion:clean(x.acceptanceCriterion,'acceptance criterion',500)})),milestones:milestones.map(x=>({name:clean(x.name,'milestone name',200),dueOffsetDays:Number(x.dueOffsetDays),feeCents:Number(x.feeCents)})),assumptions:(v.assumptions||[]).map(x=>clean(x,'assumption',500))};if(p.currency!=='USD'||p.milestones.some(x=>!Number.isInteger(x.dueOffsetDays)||x.dueOffsetDays<0||!Number.isInteger(x.feeCents)||x.feeCents<0))throw new Error('proposal amounts invalid');p.totalFeeCents=p.milestones.reduce((s,x)=>s+x.feeCents,0);if(!p.totalFeeCents)throw new Error('proposal fee required');return p}
const operations={calendar:{create_discovery:['caseRef','startAt','durationMinutes','attendeeRef']},document_store:{create_proposal:['caseRef','proposalDigest']},messaging:{deliver_proposal:['caseRef','recipientRef','proposalReceipt','decisionRef']},crm:{create_engagement:['caseRef','clientRef','proposalReceipt']}};
function job(provider,operation,payload,key){const fields=operations[provider]?.[operation];if(!fields)throw new Error('unsupported provider operation');noSecrets(Object.keys(payload));if(canonical(Object.keys(payload).sort())!==canonical([...fields].sort())||fields.some(f=>payload[f]===undefined||payload[f]===''))throw new Error('invalid provider payload');return{provider,operation,payload,idempotencyKey:key,payloadDigest:digest(payload)}}
function retry(a,r,max=5){const n=a+1;return!r||n>=max?{status:'dead_letter',attempts:n}:{status:'retry',attempts:n,delaySeconds:Math.min(900,2**n+n*3)}}function sign(s,e){if(!s||s.length<32)throw new Error('secret too short');return crypto.createHmac('sha256',s).update(canonical(e)).digest('hex')}function verify(s,e,x){if(!/^[a-f0-9]{64}$/i.test(x||''))return false;const a=Buffer.from(sign(s,e),'hex'),b=Buffer.from(x,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function key(h){const k=Buffer.from(String(h||''),'hex');if(k.length!==32)throw new Error('key invalid');return k}function encrypt(v,h,ver,aad){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(h),iv);c.setAAD(Buffer.from(aad));const out=Buffer.concat([c.update(JSON.stringify(v)),c.final()]);return{algorithm:'aes-256-gcm',keyVersion:ver,iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64'),ciphertext:out.toString('base64')}}function decrypt(e,h,aad){const d=crypto.createDecipheriv('aes-256-gcm',key(h),Buffer.from(e.iv,'base64'));d.setAAD(Buffer.from(aad));d.setAuthTag(Buffer.from(e.tag,'base64'));return JSON.parse(Buffer.concat([d.update(Buffer.from(e.ciphertext,'base64')),d.final()]))}
module.exports={states,canonical,digest,intake,qualify,transition,proposal,job,retry,sign,verify,encrypt,decrypt};
